name: PRINTING WORKFLOW

on:
  workflow_run:
    workflows:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print actions github builtin variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
